name: Machine Build BOSS
on: [push, workflow_dispatch]

jobs:
  generation_apk:
    runs-on: ubuntu-22.04
    steps:
      - name: Recupere le code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Preparation des outils Android
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5-dev libssl-dev unzip zip libffi-dev cmake
          pip install --upgrade pip
          pip install cython==0.29.33 buildozer

      - name: Fabrication de l APK BOSS
        run: |
          buildozer -v android debug
